INSERT INTO habilidade VALUES ('GIRAR','GIRA E DA DANO CONTINUO AO INIMIGO');
INSERT INTO habilidade VALUES ('SOCO', 'SOCA OS INIMIGOS');
INSERT INTO habilidade VALUES ('APUNHALAR','ESFAQUEIA O INIMIGO');
INSERT INTO habilidade VALUES ('DURMA','FAÇA O INIMIGO DORMIR');
INSERT INTO habilidade VALUES ('CONFUSAO', 'DIMINUA O DANO E A DEFESA DO INIMIGO')
